##############################################
#      Spring Profile Configuration          #
##############################################
spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+1

##############################################
#            Server Configuration            #
##############################################
server:
  port: 6000
  error:
    include-message: always

logging:
  level:
    web: DEBUG #for additional information

springdoc:
  api-docs:
    path: /api-docs
    title: API Documentation
    description: API Documentation

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method





